### PR TITLE
Added selenium web auto script

### PR DESCRIPTION
**Pull request by mthomati**
I added a new python script to do web automation using the python module called selenium.  Please review code and advise if any changes (or corrections) are needed.  Thanks!

### CODE REVIEW

**Comment by YourGirlCeleste** [comment]
Looks good, can you put the code that opens the web browser and inserts the URL into a function?

**Comment by mthomati** [comment]
I updated the code to put all components into a class object which will give us flexibility for adding additional methods when needed.  When the code runs it will run the main function which will create a new object and run the method which will open the URL.

**Comment by YourGirlCeleste** [comment]
Great change! The last thing that needs to be added to the project is a README file that contains a brief explanation of the seletest.py file. After that, I'll do the merge.

**Comment by mthomati** [comment]
Added README file to repo

**Comment by YourGirlCeleste** [comment]
File looks good, merging now!

**Pull request merged**
